########################################################
# Jykell 配置
########################################################
# markdown解释器和解释器插件
markdown: redcarpet
redcarpet:
  extensions: ["fenced_code_blocks", "footnotes", "tables"]
# 分页插件
gems: [jekyll-paginate]
# 代码高亮插件
highlighter: pygments
# 网站根路径，使用http://localhost:port/{{baseurl}}来访问网站
# baseurl: /pasper
baseurl:
# 博客分页大小
paginate: 5
# 博客分页的路径
paginate_path: page:num
# 博客生成后的访问路径
permalink: blog/:title
# permalink: /author/:username
# permalink: /tag/:tag
# 博客的语言环境
language: 'en-uk'
# 指定端口号，本地使用jekyll s的时候，可以使用http://localhost:port来访问
port: 3000
# 网站生成的目录路径，此路径应该在.gitignore上被勿略
destination: _site

########################################################
# 网站信息
########################################################
# 首页博客标题
name: "Welcome to Yan's Blog"
# 首页图片
cover: 'assets/images/cover1.jpg'
# 博客Logo
logo: 'assets/images/logo.png'
# 首页博客副标题
description: "What wakes you up every morning is not the bell,but your dream!!"
# 博客访问地址
address: 'http://mia2002.cn'
# address: 'http://127.0.0.1:4000'

########################################################
# 作者信息
########################################################
# 作者名
author: 'Yan'
# 昵称
nickname: yanyan
# 作者简介
bio: '一只正在学飞的小菜鸟'
# 作者居住地
location: '广州，广东'
# 作者主页
url: 'https://github.com/mia2002'
# 头像
image: 'assets/images/head.jpg'

########################################################
# 评论系统
########################################################
# comments_duoshuo: pasper # 多说
comments_disqus: mia2002 # disqus

########################################################
# 网站统计分析
########################################################
#analytics_google: UA-xxxxxxxx-x
#analytics_baidu: '//hm.baidu.com/hm.js?0705c3d796ab210d7657f87eba730be2'

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...

# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: false
lsi: false

#注意修改.travis.yml以支持持续集成

exclude:
  - vendor
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - .travis.yml
  - LICENSE.txt
